apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: GreenDeployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: GreenDeployment
  template:
    metadata:
      labels:
        app: GreenDeployment
    spec:
      containers:
        - image: yehia14/capstone
          imagePullPolicy: Always
          name: GreenDeployment
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: green-deployment
  labels:
    app: GreenDeployment
spec:
  type: LoadBalancer
  selector:
    app: GreenDeployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP