apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-deployment
  template:
    metadata:
      labels:
        app: green-deployment
    spec:
      containers:
        - image: yehia14/capstone
          imagePullPolicy: Always
          name: green-deployment
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: green-deployment
  labels:
    app: green-deployment
spec:
  type: LoadBalancer
  selector:
    app: green-deployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP