apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsproject5
  labels:
    app: devopsproject5
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsproject5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devopsproject5
    spec:
      containers:
        - image: 01141942205/devopsproject5
          imagePullPolicy: Always
          name: devopsproject5
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devopsproject5
  labels:
    app: devopsproject5
spec:
  type: LoadBalancer
  selector:
    app: devopsproject5
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP