version: 2.1

jobs:
  Lint HTML:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/repo

    steps:
      - checkout
  
      - run:
          name: installing tidy
          command: |
            sudo apt-get install tidy -y

      - run:
          name: Linting HTML
          command: |
            tidy -q -e *.html


  Building Docker Image: 
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Docker-configuration
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker build -t yehia14/capstone
            docker push yehia14/capstone     

workflows:
  main:
    jobs:
      - Lint HTML
      - Building Docker Image