version: 2.1

jobs:
  Lint HTML:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/repo

    steps:
      - checkout
  
      - run:
          name: installing tidy
          command: |
            sudo apt-get install tidy -y

      - run:
          name: Linting HTML
          command: |
            tidy -q -e *.html


  Building Docker Image: 
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Docker-configuration
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker build -t yehia14/capstone .
            docker push yehia14/capstone 

  Deploying to EKS:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: GreenDeployment
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: Capstone/GreenDeployment

  testing:
    executor: aws-eks/python3
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: GreenDeployment
      - run:
          name: Test cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
                      
orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.11.2
workflows:
  main:
    jobs:
      - Lint HTML
      - Building Docker Image:
          requires:
            - Lint HTML
      - aws-eks/create-cluster:
          requires:
            - building
      - Deploying to EKS:
          requires:
            - aws-eks/create-cluster
      - testing:
          requires:
            - Deploying to EKS