version: 2.1

jobs:
  Lint HTML:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/repo

    steps:
      - checkout
  
      - run:
          name: Linting HTML
          command: |
            sudo apt-get install tidy -y
            tidy -q -e *.html

workflows:
  main:
    jobs:
      - Lint HTML